[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "formatjs custom transform visitor for SWC"
edition     = "2021"
license     = "MIT"
name        = "swc-formatjs-visitor"
repository  = "https://github.com/kwonoj/swc-plugin-formatjs"
version     = "0.0.1"

[dependencies]
icu-messageformat-parser = { version = "0.0.1", path = "../icu-messageformat-parser", features = ["utf16"] }
swc_core = { version = "0.23.13", features = ["common", "ecma_visit"] }
regex      = "1.6.0"
once_cell  = "1.14.0"
serde          = { version = "1.0.143", features = ["derive"] }
serde_json      = "1.0.83"

[dev-dependencies]
pretty_assertions = "1.3.0"
