[package]
name = "icu-messageformat-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_repr = "0.1"
regex          = "1.6.0"
once_cell      = "1.14.0"

[dev-dependencies]
testing = "0.30.8"
serde_json              = "1.0.83"
similar-asserts = "1.4.2"