[package]
edition = "2021"
name    = "icu-messageformat-parser"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
langtag    = "0.3.2"
once_cell  = "1.14.0"
regex      = "1.6.0"
serde      = { version = "1.0.144", features = ["derive"] }
serde_repr = "0.1"

[dev-dependencies]
serde_json      = "1.0.83"
similar-asserts = "1.4.2"
testing         = "0.30.8"
